---
- type: healing
  etype: temple
  dtype: service
  value: 1
  weight: 1
  effect: hurt
  equip: false
  inv: false
- type: curing
  etype: temple
  dtype: service
  value: 1
  weight: 1
  effect: poison
  equip: false
  inv: false
- type: drink
  message: The drink quenches your thirst.
  etype: tavern
  dtype: service
  value: 1
  weight: 1
  effect: thirsty
  equip: false
  inv: false
- type: meal
  message: The meal fills you up.
  etype: tavern
  dtype: service
  value: 1
  weight: 1
  effect: hungry
  equip: false
  inv: false
- type: training
  etype: guild
  dtype: service
  value: 1
  weight: 1
  effect: level
  equip: false
  inv: false
